### ISSUE TITLE
ModalBottomSheet is not drawn full screen when in landscape mode

### ISSUE THREAD

**Issue by AdamGrzybkowski** [composablehorizons/compose-unstyled#27]
I've noticed that the `ModalBottomSheet` and the `Scrim` component are not drawn on full screen on some devices. So far I was able to reproduce the issue on Pixel 6 and 9pro. Both have camera cutouts so this might be related to that. 

Here's a screenshot showing the problem:
<img width="843" alt="Screenshot 2024-10-10 at 15 06 55" src="https://github.com/user-attachments/assets/82d3749c-ad1c-4d60-af7b-0fec950cef1b">

You can see that the main content with the button to show the modal is drawn to the very left side of the screen. Modal (with the red background) and the Scrim have some kind of an innset applied. 

I have created [this repo](https://github.com/AdamGrzybkowski/ModalBottomSheetTest) in case you can't reproduce it. It's pretty much a new app with modal code copied from [here](https://composeunstyled.com/modal-bottom-sheet/#drawing-behind-the-nav-bar).

**Comment by alexstyl** [comment]
Thanks for creating the repo. Will have a look asap.

Is it safe to say this happens on all version of Android?

**Comment by alexstyl** [comment]
I was able to reproduce it using the Pixel 6 Pro emulator. Investigating and will let you know.

**Comment by alexstyl** [comment]
Fixed. It will be part of the next version. Will post here when it's released

**Comment by alexstyl** [comment]
The fix is in 1.15.0. Will be available shortly on maven central.

**Comment by AdamGrzybkowski** [comment]
That was fast! Thanks @alexstyl 🎉
