### ISSUE TITLE
styling-the-system-bars sections includes code that won't compile: `Color.Transparent`

### ISSUE THREAD

**Issue by ColtonIdle** [composablehorizons/compose-unstyled#28]
Had to update `Color.Transparent` to val transparentColor = LocalContext.current.resources.getColor(android.R.color.transparent)

https://composeunstyled.com/modal-bottom-sheet/#styling-the-system-bars

**Comment by alexstyl** [comment]
there is no mention of `Color.Transparent` in the link you shared. do you mean `Color.TRANSPARENT`?

**Comment by ColtonIdle** [comment]
yep. just checked it is indeed `Color.TRANSPARENT`

**Comment by ColtonIdle** [comment]
ooh. TIL of .toArgb. Thanks!
