### ISSUE TITLE
Window.setDimAmount() doesn't work by default with Dialog

### ISSUE THREAD

**Issue by AdamGrzybkowski** [composablehorizons/compose-unstyled#34]
Code like this:
```
Dialog(state = rememberDialogState(initiallyVisible = true)) {
        DialogPanel(
            modifier = Modifier
                .fillMaxSize(),
        ) {
            val window = LocalModalWindow.current
            LaunchedEffect(Unit) {
                window.setDimAmount(0.2f)
            }
        }
}
```
won't work by default. To make the `setDimAmount` work we have to set a proper flag first:
```
window.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND)
```

This could just as well be an intended behavior, but I noticed the difference while migrating from the material Dialog.

**Comment by alexstyl** [comment]
The dimming of the winodw is done using the Scrim() composable.

Did you try using that instead?

**Comment by AdamGrzybkowski** [comment]
I tried it now and it works, thank you! 

I've skipped that part of the docs assuming I can handle it like with the material Dialog and missed it.

**Comment by alexstyl** [comment]
Glad it works. If you have other issues, feel free to open a new issue. Closing this
