### ISSUE TITLE
Add Sheet confirmValueChange callback

### ISSUE THREAD

**Issue by TheKeeperOfPie** [composablehorizons/compose-unstyled#45]
Wiring this up manually ended up being more complicated than I expected, and I can't get a working modal.

Essentially I have a persistent M3 `BottomSheetScaffold` right now which is a form that the user submits. If the user makes a change and then swipes the sheet away, I use M3's `confirmValueChange` to block the swipe down* and prompt them with a dialog to either confirm the exit or save the edits.

I can't find an equivalent in Composables Core. It seems difficult to block `SheetDetents.Hidden`, which I think I can approximate by swapping the `detents` list, removing/adding `.Hidden` as necessarily to disable the swipe down. But I actually don't want to block the swipe itself. If a user initiates a swipe, I want it to succeed and only prompt them after, so that swiping down is still a valid indication from the user to exit the form.

*Note that this is currently broken in M3 from what I understand due to a bug, which is what caused me to look for alternatives and end up here. I have an extremely hacky solution right now observing the expand/hide requests and manually reversing them, but the UX isn't great.

**Comment by alaegin** [comment]
This is a highly awaited feature for our app.
We must prevent BottomSheet from being closed while making some stuff (requests, audio recording, etc.)

**Comment by alexstyl** [comment]
Working on this today. 

It is a bit more complex than expected because I think I bumped into the behavior @TheKeeperOfPie describes on the Material Compose one.

Working on making the API and callbacks make sense, so you don't spend hours debugging it like the Material Compose one. I think it is doable tho

**Comment by alexstyl** [comment]
Made Bottom Sheet's work nicely and predictably 👍 
Working on Modal Sheet now

**Comment by TheKeeperOfPie** [comment]
Oops, hopefully I caught you early enough, but this behavior works when using the M3 modal sheet. I actually recently migrated mine to modal just to have my tests work correctly. I haven't tried to do it using Composables Core, but with M3, this works:

```
@Stable
class State {
    var formField by mutableStateOf("")

    var showExitDialog by mutableStateOf(false)
    var confirmedExit by mutableStateOf(false)
    
    var showing by mutableStateOf(false)

    fun hasChanged() = formField != ""

    fun show() {
        showing = true
        confirmedExit = false
    }
}

@Composable
fun FormBottomSheetScaffold(state: State) {
    Scaffold(...) {
        val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
        val scope = rememberCoroutineScope()
        if (state.showing) {
            ModalBottomSheet(
                sheetState = sheetState,
                onDismissRequest = {
                    if (state.hasChanged() && !state.confirmedExit) {
                        state.showExitDialog = true
                        scope.launch { sheetState.expand() }
                    } else {
                        state.showing = false
                    }
                },
            ) {
                TextField(value = state.formField, onValueChanged = { state.formField = it })
            }
        }

        if (state.showExitDialog) {
            AlertDialog(
                ...,
                onConfirm = {
                    state.hasConfirmedClose = true
                    state.showExitDialog = false
                    scope.launch { sheetState.hide() }
                },
            )
        }
    }
}
```

But to be clear, there are distinct differences between the modal and scaffold approach, and I would really want the scaffold to work. It allows you to have the sheet content always in the composition tree, and it doesn't block interacting with the app content like a dialog does.

**Comment by alexstyl** [comment]
Done. Will be released in the next version of the library
