### ISSUE TITLE
Nested scroll areas seem to not be supported

### ISSUE THREAD

**Issue by kastork** [composablehorizons/compose-unstyled#50]
Thanks for this library of code, very useful.

I'm using KMP to make a web assembly client for my backend.

I've tried to create an app where the whole view is scrollable, but then also, somewhere in the page content contains  a list that I would like to be independently scrollable.  When I try this, I get an uncaught WebAssembly exception.

Pages that don't contain the second scroll area work fine, and if I don't enclose the page with a scrollable list in a top level scroll area, that works fine too.

Is this use-case simply not supported, or is there some trick or pattern I need to follow to make it work?

I didn't include the exception data because they are unintelligible anyway, making reference to generated WASM code that is impossible to correlate with the Kotlin sources.

Thanks

**Comment by alexstyl** [comment]
Hello. Thanks for the report.

It would help speed things up if you can provide some code that reproduces your issue.

**Comment by alexstyl** [comment]
Without having more context or code, it is impossible to help.

What you describe me sounds like intended behavior in Compose, as nested scrolling is not supported. This has nothing to do with Unstyled. Try setting a fixed height (or width depending on the scroll orientation) to your inner scrolling content and see if it works.

If this is not the case, I need to see a minimum reproducible code to help further.

**Comment by kastork** [comment]
@alexstyl  Thought I'd let you know.  Giving the inside list's column a fixed height does work. Thanks for that idea.

**Comment by alexstyl** [comment]
Awesome
